project:
  type: book
  output-dir: docs

book:
  title: "Curso Java"
  language: "pt-BR"
  chapters:
    - index.qmd
    - chapters/aula-00-orientacao-a-objetos.qmd
    - chapters/aula-01-introducao-a-programacao-orientada-a-objetos.qmd
    - chapters/aula-02-primeiros-passos-no-ambiente-de-programacao.qmd
    - chapters/aula-03-fundamentos-java.qmd
    - chapters/aula-04-variaveis-e-tipos-primitivos.qmd
    - chapters/aula-05-casting-e-promocao.qmd
    - chapters/aula-06-condicionais.qmd
    - chapters/aula-07-loops.qmd
    - chapters/aula-08-conceitos-de-orientacao-a-objetos.qmd
    - chapters/aula-09-modificadores-de-classe-encapsulamento-e-atributos-de-classe.qmd
    - chapters/aula-heranca.qmd
    - chapters/aula10-polimorfismo.qmd
    - chapters/aula12-strings.qmd
    - chapters/aula13-arrays-atividade.qmd
    - chapters/aula13-arrays.qmd
    - chapters/aula14-collections.qmd

format:
  html:
    theme: cosmo
    toc: true
    number-sections: false
    fig-responsive: true
    code-copy: true
    include-after-body:
      - assets/keyboard-nav.js

execute:
  freeze: auto

lang: pt-BR
